### ISSUE TITLE
Write tests for PiggyBank

### ISSUE THREAD

**Issue by RajeshPatkar** [RajeshPatkarInstitute/RpISE-Component-Library#1]
Please write an comprehensive test for PiggyBank. 

The Source code is [HERE](https://github.com/RajeshPatkarInstitute/RpISE-Component-Library/blob/master/Miscellaneous/src/PiggyBank.java)

Once completed please go to [HERE](https://github.com/RajeshPatkarInstitute/RpISE-Component-Library/blob/master/Miscellaneous/tests/PiggyBankTest.java) and post your test code

**Comment by saeedd77** [comment]
Sir, 
Please check it and let me know if any improvements needed.
